travis:
  secure:
    BINSTAR_TOKEN: fGcJ9GK8hw6hBXS3N1KcP58jy6Lfp6AljkQEjZV0/IA648Q3TlwFUDzMYtfvh55WXb391v2zpg6PIIDW8pjEmQCQBN4nu9fsWRbkMk3a5UPAVqjOdiVtnmRfnv4OJFbV4ULNUdku+U09eVisvAHiFCGuGCEQj+t7UMHXWBs311LvFXblyvG+NPzggxyluZjQIr4PGXH8ISphiaUOxd7Jt7TG9qpj39O+OdJ7fLHICEI0Tb4HjmYsYJnr4W8Lky01MxZ65M/dOo1xcLMZTWd+73mStjyu/i0edKToIAjugERiIOavpW+1Z8r6F8AYlgp8Cu9b1XFUglCA4EC02Zo3UJgwG5R/W2CmVB/1gHLcey9bAcZ8pb2hdQMXxKmCTcpqrM8tz6ZNF75YUy/okF/l6Nu3QXZUuZoVb+s29oHYAzZm4YtjL71iuOE9GNcutjeUJs3+AjYWZOzHWE0FAnJgME+OFJp78vFICAN63lGz4hpqi0jtDlkjehPjmP6QjCtzcXRvFRLhLD7ia89VI+msOzACovzAK5faybtaHGjxFg1TmKGn9umK7wrmKprN8NMFiLeE/pyYXz3tjC+dZiD1sl2r40cN6BIGvEp6Ef+5NkDqV5lK3Iz+WgLFko5ghtflNcJSxG/hajxkuavEaeOrBB3f/tJaDthjc7NIW4aYwLM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
