travis:
  secure:
    BINSTAR_TOKEN: abI6eApCbK938UpUfy/BnA9DyEdBeWntx6cD9Gtp8LWVNgNaLQGZ8BcD8d76zM1bS7TFCVx0QWSaDh00f3aYT0qLH5eos9tERFw8Dv9BJFso8UT+96V+pXvdfCLs3y3Xi2hG3g85XH3vi4QAAlrCRh7KJDbglH+GrelQf7qTSQu5vh6+Hi2K/HYlrax8E1RTc4W7+xpE/yMtr4dehm0cwAmBQ9ad+R2U6FkqQYUJclsIQs7gSHcetMTie21KFqlvUViAWAaSzXAkjzy2KWcoJaTOO+YTuQzLaveAJstyDLqer0s6NKHmjewf0A2FTjUFLSqQVYBk1cAUXkoMGnqCzTFYmf2PR0PcDUpwykESmJ8bl2JdygMR3GOMuOVko2jP/Cp0go5AwUvpSEX4zjRTfG/CWY2M9rdpG9QiTLdtK/jP7HYwGG08mTMlI1Z0tfD5zu5LGR2Kml5V4nB++roCKEx39srRst88tb4qlX88yNU4FhIQd+teLardgo6jqVqx3N25sliA4beSSup8yE44uhAC5y5AJqJ8+b4g60YXtthDWinu28iqtWPbhhl7I8Fn3uBfoJy+4ICV/syHEiMnL8ZvxcozZI1o1hmcRV85lCmMUVQxnFisdRJRJ+vGIliHAl9zruw2env89LOazqUED+MV93wrV/hmLzEoj5sxhhA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
