travis:
  secure:
    BINSTAR_TOKEN: UGOF4WHO/xbXTIr1CqVBpGhtvs0lTvUijdQI0CT0o4U+/DuaOKut1D9YnbTwtOGh0fvHexU10sHn2EM+09sR8zBSVfsQoJ9Quczh7aNLJS4uVhoBrTzSh+02pLZXIv6UwuLzaj6oqA1zOMnrsJiGahStyPNnREp7Q0+OWgp4BETTezbiXW0tlAwaFfh7nx2lbaw6Py5t4k2wF+CBuApxBG8pWMLA1YIKAAiSjV97ki5Q/NqjwnMbXG3jrH4XLp0YcS68UbTg7lerylGhnRRP4g83vbV6iQlp1BW2X7UTyQtSFfsyP3aQ6kYe7yk8tWtYopWQ/yrRDEaMRIzlP7ToNtSctCtGjIjAMHoFVz3dWB43llYbm7WoEOgZrzoIq69xrPaoPrUa0biRulPi6epjRi3lsTM3JZHBwr8sMW8r+v2CPkcKBovNrwrG0F8Ho84MkcztCAgrIMDUBjq62WXjwgflvBlKGssuzm6vd108p/QbZ8R90FkAzygl2qj791PelYNDx0CU6bddfSOQknJP6ufi9IxYYie1yN1a7Uy2ZuaXl9SlytLVbm8cdlmoruU0ullWO0/yEmAK5BYdOuGdSmtbEN8Z1wwFaapHQ1e7uGtmfOeaAscfqFB1q1wNSSqBJXJrKqJ5B2JD5MmTbPA50zFJvNUOHLPGCUoz76nZNBg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
