travis:
  secure:
    BINSTAR_TOKEN: 7nIkPgmBBmj+CopDMLS1A0GUCEpz7FTiwKTo2AFta8ONwrc9KRJxMuMZeKj6whxeUYSeQPS7mzobFEPcvx2Kwu5Z8mzo+nkMuWqbDqw3hKBkNlkwnsehYnTLiW6URhJT0r4hp1iRHsCL74JNlvzJXVfkbCw/YoIYGbAr5HJ1Jl7oDdoYJLUdTN0cOS1+qFJfgupPQn31KUYWiYBHsk1a3aviM33xJknCLaPXdRDYuap26tfcrdVnN05hzHxRQ19JA8RqDT1Pxc/K8fu2IMrTBFI2gfrMyf6Eb3SvplqG6aFhDUz6YtNM5MjyQwKqgonTn6H1KYrNtbMoM6hkSg9HtKi/kWUmUx6FYVGuiQ4qF1V4itm2ZmmfiYFDMMWxdcxzmvRrKAea8dwH0DVM/1G8QNAZKnoaBKQAnRH82Lk0B54J06tCioB9WaNS4BjAVSL6xPUZvHeM9rd+zrKz++vkvpVFV6RberT0CEga5PZKH1bJzFZLjQfMGAqL61vs6Ma2N7ftWNiRDcgFqptl5wnzfw+YKpsTUGfIWJyrp8tGLyO7CnhPYN5yQltjaATbNSth0QaFOkj8bFlhGwrJYBRAL9pt8Fi1YfLggdl7rxxb8ERFLGXJH98kadEqy1kL/1ATVcq4us541PrZUEiK8lKi2vmw7KDUBQnGGiIOBx57LhY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
