travis:
  secure:
    BINSTAR_TOKEN: vtJgyrJAWZv6RkPX8gvDfUm5//WSpj8vSdJ4+eAOmgJtoYxz/CqRd+eXBYGlK8eqmfH6I61IkFoCGRPvU0DbQxlOQS/sXlc0o0UULeHManawH/9zFoN4uPTUI3d229Z07l1lzoY/t+d12aEbToxBGUSuYk39tsjZ5nND/eqUU3w/vjp1q+wzqpQOkFhPzv/SVN0CoJbsjEPnpdcmpSFhzpF5OmX9vmwNG1uf39FWKn+Wb9WZ45uyd7LYBg2F4CG/4P84Oo9Hzmz0BIDTeN4grlje0Y0WtFi3KnWbENgGo9O35UwW64ckJE6v6Ua1dFe6OZiNxk8RYdk0f/w1HZf0WmbcKRUi8t57/nA1eGDr/X5p1mh+1AwtUkMiD+zZ3H9BHmAB2YErbPydNjvgJGP0fqw891hxp3dcfxkshV/22pSrTt2B52i/3hahhgc32zcPr8I/pEoJEcNJq/9rzIeb+Uzr2RGQB9/QlP+RRZVYn4ezZsTe+c31PZLTd82QqgEMuFYnqcBQcNW4ZATWr9lWeO0ysiM3dfjoGqHQFI7rPMnZhzIux/l817Xk8z5LoAS+2+Dd8eQCSIJxdPygVcCEkZWH+5NkX+7Je/6iIark0Qi4ndE2NRLE2NLPjuyZs+YZlGDgo0CTpQlCKmpQdXoxgq8VkZ6EUooyjQs/RHf7soM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
